on: [push, pull_request]

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        go: [ "1.14.x", "1.15.x", "1.16.0-beta1" ]
    runs-on: ubuntu-latest
    name: Integration Tests, Go ${{ matrix.go }})
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: '!contains(${{ matrix.go }}, "beta") && !contains(${{ matrix.go }}, "rc")'
          go-version: ${{ matrix.go }}
      - run: go version
      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/ginkgo
      - name: Install dependencies
        run: go install
      - name: Run tests
        run: ginkgo -r -v -randomizeAllSpecs -randomizeSuites -failFast -trace integrationtests/self -- -qlog
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: qlog-{{ matrix.go }}
          path: integrationtests/self/*.qlog
